spring:
  application:
    name: employeeManagement
  data:
    mongodb:
      uri: mongodb://localhost:27017/employeeDB
  Jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  port:8080
jwt:
  expiration: 360000

logging:
  level:
    root: INFO
    com.example.employeeManagement: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg [requestId=%X{requestId}, userId=%X{userId}]%n"