spring:
  application:
    name: employeeManagement
  data:
    mongodb:
      uri: mongodb://localhost:27017/employeeDB
  Jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  port:8080

